### ISSUE TITLE
Issue Using Beveridge-Nelson Decomposition (bnd) function

### ISSUE THREAD

**Issue by Rmonkey26** [KevinKotze/tsm#1]
Hello,

I was recently trying to use the bnd function for Beveridge-Nelson decomposition. I ran into the following problem. Without being too specific this was my workflow:

data <- ts(runif(1000, 0, 1), start = c(1900,1), frequency = 12)
result <- bnd(data, nlag  = 12)

Error in rbind(coef.tmp, eye) : 
  number of columns of matrices must match (see arg 2)

This error is fixed when I go into the function and change line 10 from:

  x = yl[(nlag + 1):(length(y) - 1), 1:8]

to: 

  x = yl[(nlag + 1):(length(y) - 1), 1:nlag]

Otherwise, I have to rbind a 12 column matrix with an 8 column one and this is my error.

**Comment by KevinKotze** [comment]
Many thanks for bringing that to my attention. Have made the correction.
